### ISSUE TITLE
Safe Code Alternative

### ISSUE THREAD

**Issue by nateonline** [Jonas-Hack/Unity-Thrustmaster-T16KM-HOSAS-InputSystem#1]
Is there any way to achieve the fix you've described without the "unsafe" keyword? I'm working in a very large project with 8-10 other developers and don't want to open up the code base to unsafe code unless we really have to.

**Comment by Jonas-Hack** [comment]
Yes, there is. It took some rummaging through only half documented engine code, but I got it running. Thank you for pointing out this issue. Hope my code helps your project :)
