### ISSUE TITLE
Steering Wheel Suppot for T300 RS with Unity

### ISSUE THREAD

**Issue by hanzlawb** [Jonas-Hack/Unity-Thrustmaster-T16KM-HOSAS-InputSystem#4]
Although this is not an issue but a query. Can you guide me regarding the integration of the Thrustmaster T300 RS Steering wheel in Unity?

**Comment by Jonas-Hack** [comment]
Hi, 
Most of this repository is not completely relevant for the use-case of steering wheels. It does however build on the same basics.
Unfortunately, I do not own this steering wheel , so I cannot give you a perfect roadmap, but here we go.

In Unity's **New Input System**, there are 3 main topics, you need to know about:

1. **Input Action Assets**
    An *Input Action Asset* describes a control scheme. Any action your character might take is represented as a **Input Action**.

2. **Bindings**
   *Bindings* are used to associate *Input Actions* in an *Input Action Asset* with *buttons*. A *binding* can be seen as a file path to a button. It makes use of the data specified in the *layouts*.

3. **Layouts**
    A layout describes the *device's state* (= the data of all its buttons), as it is in the *system memory*. It lets Unity know, which information is where. For most basic devices Unity already has predefined Layouts, which you can use out of the box. 
Some devices have *additional buttons*, which are not listed in the "base device's layout" - for that case you can create *Layout Overrides*.
Some devices are only recognized as *HIDs* (Human Interface device). This is not a problem, but completely expected.

I highly recommend, you at least skim the corresponding manual pages, if you plan on doing anything advanced (beyond plug and play): 
https://docs.unity3d.com/Packages/com.unity.inputsystem@1.8/manual/ActionBindings.html
https://docs.unity3d.com/Packages/com.unity.inputsystem@1.8/manual/Layouts.html#layout-overrides


***Adding Buttons to a Layout Override***

With that said, hopefully you should not need to  worry about any of that. Unity should recognize the steering wheel as an *HID* device and work out of the box, using the usual *Input Action Editor UI*.

If it is missing some functionality, then you need to investigate its *device state* in memory manually, so you can then create a *layout override*.  That is what I did for the left-right-switch of the TM16000M.

To look at the device state:
(Menu Bar) Window -> Analysis -> Input Debugger -> (Drop Downs) Devices -> <Your Device Name> -> double click
This shows you most of the Info about the device (including the input layout. Click "State", then "Display Raw Memory" and make sure to enable "Live".

You  should now be looking at either binary or hex data. Press the button, you want to add to your layout. Observe what happens to the state of the device and analyze the binary/hex values. Pay attention to how many bits change and what bits change.

With that information, you can create (and register) a layout override (using code).


Here is what that looked like for my left-right-switch:
```C#
InputSystem.RegisterLayoutOverride(@"
            {
                ""name"" : ""T16000MWithLeftRightSwitch"",
                ""extend"" : ""HID::Thrustmaster T.16000M"",
                ""beforeRender"" : ""Update"",
                ""controls"" : [
                    { ""name"" : ""leftRightSwitch"", ""layout"" : ""Button"", ""offset"" : 0, ""bit"" : 29, ""sizeInBits"" : 1}
                ]
            }
        "); 
```
Note the "bit" = position in state, and "sizeInBits" = number of affected bits.

Here is a link to the exact same process explained by someone else:
https://forum.unity.com/threads/t-16000m-read-left-hand-right-hand-switch.873124/
This is what got my project started aswell.

My project does a number of other things aswell, but they all relate to left/right hand management, which should not be an issue with a steering wheel.

Good luck, hope I could help!
